import { ArrowLeft } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";
import { Button } from "@/components/ui/button";
import { getInsight } from "@/data/insights";
import { getService } from "@/data/services";
import { consultationUrl, SITE_URL } from "@/lib/siteConfig";

const InsightDetail = () => { const { slug } = useParams(); const insight = getInsight(slug); if (!insight) return <div className="container py-32">Research note not found.</div>; return <div className="min-h-screen bg-background"><SEOHead title={insight.title} description={insight.excerpt} url={`${SITE_URL}/insights/${insight.slug}`} type="article" schema={{ "@context": "https://schema.org", "@type": "Article", headline: insight.title, datePublished: "2026-09-20", author: { "@type": "Organization", name: insight.author }, publisher: { "@type": "Organization", name: "ResearchReady Services" } }} /><Header /><main className="pt-20"><article><header className="border-b border-border py-14 lg:py-20"><div className="container max-w-4xl"><Link to="/insights" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Research Insights</Link><div className="mt-10 flex gap-3 text-xs font-semibold uppercase tracking-widest text-accent"><span>{insight.category}</span><span>·</span><span>{insight.readingTime}</span></div><h1 className="mt-5 font-playfair text-4xl leading-tight text-primary sm:text-5xl">{insight.title}</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">{insight.excerpt}</p><p className="mt-5 text-sm text-muted-foreground">{insight.author} · {insight.date}</p></div></header><div className="container max-w-3xl py-14 lg:py-20">{insight.sections.map((section) => <section className="mb-12" key={section.heading}><h2 className="font-playfair text-2xl text-primary">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-5 text-base leading-8 text-foreground/80">{paragraph}</p>)}</section>)}<aside className="border-y border-border py-8"><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Related research support</p><div className="mt-4 flex flex-wrap gap-3">{insight.relatedServices.map((slug) => { const service = getService(slug); return service ? <Button variant="outline" asChild key={slug}><Link to={`/services/${slug}`}>{service.shortTitle}</Link></Button> : null; })}</div></aside><div className="mt-12 bg-primary p-8 text-primary-foreground"><h2 className="font-playfair text-2xl">Working through a related research problem?</h2><p className="mt-3 text-primary-foreground/70">Share the context and we will assess what kind of support is appropriate.</p><Button className="mt-6" variant="gold" asChild><Link to={consultationUrl()}>Discuss Your Research</Link></Button></div></div></article></main><Footer /></div>; };
export default InsightDetail;