import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";
import { Button } from "@/components/ui/button";
import { openConsentSettings } from "@/lib/consent";
import { CONTACT_EMAIL, SITE_URL } from "@/lib/siteConfig";

const sections = [
  ["Information we collect", "When you submit an enquiry or request a consultation, we may collect your name, email, WhatsApp number, country, research level, discipline, project details, deadline, contact preference and any document you choose to upload. Account, support and payment records may also be collected when you use those services."],
  ["How information is used", "We use this information to assess research enquiries, define suitable support, communicate with you, provide agreed services, maintain account and support functions, protect the service and meet legal obligations."],
  ["Research documents", "Enquiry documents are stored in a private area and made available to authorised staff for assessment. Please avoid uploading information that is not needed for the enquiry."],
  ["Service providers and disclosure", "We use service providers for hosting, secure storage, email, payments and website measurement. We do not sell personal information. Information may also be disclosed when required by law, to protect the service or when you direct us to do so."],
  ["Analytics and advertising measurement", "Only after you accept, Google Analytics receives page views, service views, interaction events and device information for site measurement. Meta receives page and interaction events for advertising measurement and optimisation. Both may receive campaign identifiers such as UTM values and a referrer; form names, emails, phone numbers and document contents are not sent as event fields. We do not load either provider's measurement tags while consent is unresolved or declined."],
  ["Your choices", "You can accept or reject measurement and change your choice at any time using Cookie settings. We retain the consent choice, notice version and decision time in local browser storage so the site can honour your preference; changing or clearing that record withdraws the stored choice. You may also request access, correction or deletion of personal information, subject to legal and operational retention requirements."],
  ["Security and retention", "We use technical and organisational safeguards appropriate to the information handled. Information is retained only as long as necessary for the purpose collected, service delivery, dispute handling and legal obligations. No internet transmission can be guaranteed completely secure."],
];

const PrivacyPolicy = () => <div className="min-h-screen bg-background"><SEOHead title="Privacy Policy" description="How ResearchReady handles research enquiries, uploaded documents, communications and consent-based website measurement." url={`${SITE_URL}/privacy`} /><Header /><main className="pt-24 pb-20"><div className="container max-w-4xl"><p className="eyebrow">Privacy</p><h1 className="font-playfair text-4xl text-primary sm:text-5xl">Privacy Policy</h1><p className="mt-4 text-sm text-muted-foreground">Last updated: 20 September 2026</p><div className="mt-12 space-y-10">{sections.map(([title, copy], index) => <section key={title}><h2 className="font-playfair text-2xl text-primary">{index + 1}. {title}</h2><p className="mt-3 leading-8 text-muted-foreground">{copy}</p>{title === "Analytics and advertising measurement" && <Button className="mt-5" variant="outline" onClick={openConsentSettings}>Cookie settings</Button>}</section>)}<section><h2 className="font-playfair text-2xl text-primary">8. Contact</h2><p className="mt-3 leading-8 text-muted-foreground">Questions or privacy requests can be sent to <a className="font-medium text-primary underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p></section></div></div></main><Footer /></div>;
export default PrivacyPolicy;