import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";
import { Button } from "@/components/ui/button";
import { getService } from "@/data/services";
import { consultationUrl, SITE_URL } from "@/lib/siteConfig";
import { useEffect } from "react";
import { trackServiceView } from "@/lib/analytics";

const ServiceDetail = () => { const { slug } = useParams(); const service = getService(slug); useEffect(() => { if (service) trackServiceView(service.title, "service_page"); }, [service]); if (!service) return <div className="container py-32"><p>Service not found.</p><Link to="/services">View services</Link></div>; return <div className="min-h-screen bg-background"><SEOHead title={service.title} description={service.summary} keywords={service.keywords} url={`${SITE_URL}/services/${service.slug}`} schema={{ "@context": "https://schema.org", "@type": "Service", name: service.title, description: service.summary, provider: { "@type": "Organization", name: "ResearchReady Services" } }} /><Header /><main className="pt-20"><section className="border-b border-border py-16 lg:py-24"><div className="container grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><Link to="/services" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground"><ArrowLeft className="h-4 w-4" /> All services</Link><p className="eyebrow mt-10">{service.category}</p><h1 className="font-playfair text-4xl leading-tight text-primary sm:text-5xl">{service.problem}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{service.summary}</p><Button className="mt-8" variant="gold" size="lg" asChild><Link to={consultationUrl(service.title)}>Discuss This Research Problem <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="border-l-2 border-accent bg-secondary p-7 lg:p-10"><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Areas of support</p><ul className="mt-7 space-y-5">{service.capabilities.map((item) => <li key={item} className="flex gap-3 text-base font-medium"><Check className="mt-0.5 h-5 w-5 shrink-0 text-accent" />{item}</li>)}</ul></div></div></section><section className="py-16"><div className="container max-w-4xl"><h2 className="section-title">Support that protects the integrity of your research</h2><div className="mt-7 grid gap-8 text-muted-foreground md:grid-cols-2"><p className="leading-7">ResearchReady works collaboratively. We help clarify choices, strengthen methods, analyse evidence, interpret results and refine scholarly or professional outputs.</p><p className="leading-7">The scope is defined around your actual research requirements. We do not promise guaranteed approvals, publications or outcomes, and support must be used in line with applicable academic integrity standards.</p></div></div></section></main><Footer /></div>; };
export default ServiceDetail;