import { ArrowRight, Check } from "lucide-react";
import { Link } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";
import { Button } from "@/components/ui/button";
import { serviceGroups, services } from "@/data/services";
import { consultationUrl, SITE_URL } from "@/lib/siteConfig";

const Services = () => <div className="min-h-screen bg-background"><SEOHead title="Research Support Services" description="Explore professional support for dissertations, methodology, literature reviews, data analysis, publishing and organisational research." url={`${SITE_URL}/services`} /><Header /><main className="pt-20"><section className="border-b border-border py-16 lg:py-24"><div className="container grid max-w-6xl gap-8 lg:grid-cols-[.65fr_1.35fr]"><p className="eyebrow">Research services / Capabilities</p><div><h1 className="font-playfair text-4xl leading-[1.12] text-primary sm:text-5xl lg:text-6xl">Research support built around the problem you're actually trying to solve.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">From research question to defensible analysis, our work focuses on method, evidence, interpretation, refinement and professional presentation.</p></div></div></section><section className="editorial-section"><div className="container space-y-20">{serviceGroups.map((group, groupIndex) => <div key={group.title} className="grid gap-8 border-t border-border pt-8 lg:grid-cols-[.7fr_1.3fr]"><div><span className="text-xs text-accent">0{groupIndex + 1}</span><h2 className="mt-6 font-playfair text-3xl text-primary">{group.title}</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">{group.description}</p></div><div className="grid gap-px border border-border bg-border sm:grid-cols-2">{services.filter((service) => service.category === group.title).map((service) => <Link key={service.slug} to={`/services/${service.slug}`} className="group bg-background p-6 transition-colors hover:bg-card"><h3 className="font-playfair text-xl text-primary group-hover:text-accent">{service.shortTitle}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{service.summary}</p><span className="mt-6 inline-flex items-center gap-1 text-xs font-semibold uppercase tracking-wider">Explore <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></div>)}</div></section><section className="border-y border-border bg-secondary py-14"><div className="container flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="font-playfair text-3xl text-primary">Complex projects are scoped, not commoditised.</h2><p className="mt-2 text-muted-foreground">Share the research problem and receive a clear assessment of what support is appropriate.</p></div><Button variant="gold" size="lg" asChild><Link to={consultationUrl()}>Request a Research Assessment</Link></Button></div></section></main><Footer /></div>;
export default Services;