import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";
import { Button } from "@/components/ui/button";
import { Mail, MessageCircle } from "lucide-react";
import { CONTACT_EMAIL, SITE_URL, whatsappUrl } from "@/lib/siteConfig";
import { trackWhatsAppClick } from "@/lib/analytics";

const Support = () => <div className="min-h-screen bg-background"><SEOHead title="Contact ResearchReady" description="Contact ResearchReady about an existing research enquiry, consultation or client project." url={`${SITE_URL}/support`} /><Header /><main className="pt-24 pb-20"><div className="container max-w-5xl"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><p className="eyebrow">Client support</p><div><h1 className="font-playfair text-4xl text-primary sm:text-5xl">Continue a research conversation.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">For an existing enquiry or project, include the name and email used previously so we can locate the relevant context.</p></div></div><div className="mt-16 grid gap-px border border-border bg-border md:grid-cols-2"><div className="bg-background p-7 lg:p-9"><Mail className="h-6 w-6 text-accent" /><h2 className="mt-10 font-playfair text-2xl text-primary">Email support</h2><p className="mt-3 leading-7 text-muted-foreground">Send the details of your enquiry or project and any reference information.</p><Button className="mt-7" asChild><a href={`mailto:${CONTACT_EMAIL}?subject=ResearchReady%20Support`}>Email ResearchReady</a></Button></div><div className="bg-background p-7 lg:p-9"><MessageCircle className="h-6 w-6 text-accent" /><h2 className="mt-10 font-playfair text-2xl text-primary">WhatsApp</h2><p className="mt-3 leading-7 text-muted-foreground">Use WhatsApp when it is your preferred way to continue the conversation.</p><Button className="mt-7" variant="outline" asChild><a href={whatsappUrl("existing ResearchReady enquiry")} target="_blank" rel="noopener noreferrer" onClick={() => trackWhatsAppClick("support_page")}>Discuss on WhatsApp</a></Button></div></div></div></main><Footer /></div>;
export default Support;